# qt projects compiler bsed on fedora:latest

FROM fedora
MAINTAINER "Ammar Najjar <najjarammar@gmail.com>"
LABEL Description="This image is used to build qt projects" Version="1.0"

RUN dnf update -y
RUN dnf install -y qt qt-devel make gcc-c++
